# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: sdk

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'update --global VirtoCommerce.GlobalTool'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Starting VC build"
      vc-build compress
      Write-Host "VC build completed"
    pwsh: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\s\artifacts'
    publishLocation: 'pipeline'